services:
    web:
        build: .
            args:
                DOMAIN: ${DOMAIN}
        container_name: azuriom-web
        ports:
            - "80:80"
            - "443:443"
        networks:
            - azuriomnet
        depends_on:
            - db
        volumes:
            - ./azuriom_data:/var/www/azuriom
            - ./plugins:/var/www/azuriom/plugins
        environment:
            USE_SSL: ${USE_SSL}
            DOMAIN: ${DOMAIN}
            DB_HOST: db
            

    db:
        image: mariadb:latest
        container_name: azuriom-db
        environment:
            MYSQL_ROOT_PASSWORD: azuriom
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - azuriomnet

networks:
    azuriomnet:

volumes:
    azuriom_data:
    db_data:
